### ISSUE TITLE
Implement a Menu to customize specific options

### ISSUE THREAD

**Issue by iSnackyCracky** [iSnackyCracky/KeePassRDP#1]
Add a menu (below the *Tools* in the main menu) to configure things like
- KeePassRDP entry-context-menu location (directly accessible or below the *URL(s)* menu)
- Keyboard shortcuts
- Additional mstsc.exe Parameters

**Comment by agrifus** [comment]
Hello!
How to open RDP in full screen through this plugin?
By default, it remembers the screen resolution that was last opened.

**Comment by iSnackyCracky** [comment]
Hi,
> Hello!
> How to open RDP in full screen through this plugin?

unfortunatly this is currently not possible.

> By default, it remembers the screen resolution that was last opened.

This is by design, because the plugin just launches the default `mstsc.exe` - which itself uses the `%USERPROFILE%\Documents\Default.rdp` file for it's settings.

I'll try to add options like these to the menu (hopefully) coming in the future.
I don't really get to work on this project at the moment though.

**Comment by agrifus** [comment]
this turned out to be a very necessary option.
please try to add.
in fact, to open in full screen you need to add the parameter "/f"

**Comment by iSnackyCracky** [comment]
I'll try to add this asap. Would you prefer a separate setting to turn on/off or like an additional, sort of "one-time" parameter (like the current `/admin` implementation)?

**Comment by agrifus** [comment]
so that by default it always opens in full screen mode.
also arrange any of the options

**Comment by iSnackyCracky** [comment]
> so that by default it always opens in full screen mode.

Okay, I already looked into this a bit today and probably have a bit spare time on the weekend, maybe I get to implement this already.
> also arrange any of the options

Could you elaborate a bit more on this? I'm not sure that I get what you mean here.

**Comment by iSnackyCracky** [comment]
> so that by default it always opens in full screen mode.

got it - check out the [new release version 1.6.0](https://github.com/iSnackyCracky/KeePassRDP/releases/tag/v1.6.0)

**Comment by agrifus** [comment]
thank you very much!

**Comment by iSnackyCracky** [comment]
Shortcut customization done in c5e2698
Won't implement context-menu-location as I think it would bloat up the URL menu too much.
