### ISSUE TITLE
Repository is missing a license

### ISSUE THREAD

**Issue by stefan-muc** [iSnackyCracky/KeePassRDP#14]
**Is your feature request related to a problem? Please describe.**
This repository / this KeePass Plugin is missing a license. So as a user I don't know where and how I'm allowed to use this plugin

**Describe the solution you'd like**
Provide a license. I would prefer an OpenSource one

**Describe alternatives you've considered**
not using the plugin to not be in legal danger

**Additional context**
included third-party libraries:
ObjectListView uses [GPL v3](https://sourceforge.net/p/objectlistview/code/HEAD/tree/cs/trunk/COPYING)
CredentialManagement uses [Apache 2.0](https://github.com/ilyalozovyy/credentialmanagement/blob/master/LICENSE)

**Comment by iSnackyCracky** [comment]
Hi @stefan-muc,

thanks for bringing this up.
I've looked into some possible options and decided to use the GPL v3 License for this project.

**Comment by stefan-muc** [comment]
Hi @iSnackyCracky - thank you very much for your fast response!
