### ISSUE TITLE
Credential manager wont pop-up

### ISSUE THREAD

**Issue by Johnwulp** [iSnackyCracky/KeePassRDP#17]
Hi,

Im using keepass 2.46 portable, and the lastest plugin 1.12.0.233.
In my database I created a group, and below that a RDP group. 
The accounts are in the group 'Test':
![Example 1](https://i.imgur.com/oLzDrvd.png)

The RDP entry's in group 'RDP':
![Example 2](https://i.imgur.com/vgLYpaY.png)

The RDP entry is configured as followed:
![Example 3](https://i.imgur.com/siyW9pE.png)

The problem is that for some reason the credential manager isn't popping up by pressing <CTRL> + M. 
If i configure the correct username and password for a single entry, the connection works as expected.

**Comment by iSnackyCracky** [comment]
Hi @Johnwulp,

The title of entries you want to get Listed in the credpicker need to match a specified RegEx pattern.
By default this is: `.*(domain|domänen|local|lokaler|windows).*(admin|user|administrator|benutzer|nutzer).*`
You can currently only customize the Parts inside the parentheses by going to the KeePassRDP Options menu and adding Pre- or Postfixes.

In your Example, as the accounts are simply named like "Account *" it should be enough to add "Account" to the Prefixes like this:
![image](https://user-images.githubusercontent.com/20481463/94122206-92aff580-fe52-11ea-8119-29ffda37a76c.png)

I'm still working on making this RegEx pattern more customizable in general (for example implementing the features mentioned in #15). But this will still take some time.

**Comment by Johnwulp** [comment]
Hi @iSnackyCracky ,

Thanks for explaning this behaviour, after settings these options, it works as expected :-)
