### ISSUE TITLE
Support Gateways (mstsc /g)

### ISSUE THREAD

**Issue by wexman** [iSnackyCracky/KeePassRDP#18]
I have a remote computer that needs to use a gateway (the /g parameter to mstsc.exe). Is there any chance we could support this feature?

**Comment by iSnackyCracky** [comment]
Hi @wexman,

first of all, thanks for the suggestion.
I am currently working on more customizability on a "per entry" basis (such as #15).
I'm thinking this could fall into a similar kind of optional parameter "per entry" too. (AFAIK you need to specify the gateway per target host.)
So I'll definitely look into this. This might still take a while though.

**Comment by NETertainer** [comment]
Using v2.0 onwards KeePassRDP will add a tab to the edit entry dialog that allows to specify custom parameters to be passed to mstsc.exe for that entry.
