### ISSUE TITLE
KeePassRDP does not fill in credentials correctly when Store as Windows credentials is enabled

### ISSUE THREAD

**Issue by scorbin-ewi** [iSnackyCracky/KeePassRDP#20]
KeePassRDP does not automatically fill in credentials, or fills in wrong credentials as indicated by message indicating 'The logon attempt failed' beneath login box.
![LoginFailed](https://user-images.githubusercontent.com/57776961/107650364-07d66880-6c44-11eb-940f-d2b53299f254.png)

Sometimes this message appears and other times it just asks for credentials.  If 'Store as Windows credentials' option is disabled the plugin works just as expected.  NTLM-auth is not strictly prohibited on the local network and the attempt is from a workstation on the local network connecting to Windows server 2016 and also with Windows Server 2012.  I tried reinstalling the plugin with no luck.  When the login box appears, with or without the login failed message, simply pasting the credentials copied from the KeePass entry logs in without issue.

We do monitor log files and report for NTLM logins on all servers and workstations and no log entries were generated on either the workstation or the servers being logged into.  In fact a failed login event was not even generated on either machine.  Also the account was not locked out after many invalid attempts even though lockout after 3 invalid logins is the domain policy.

I usually use references to another KeePass entry for my username and password and I have tried with the references and with implicitly defined username and password.

KeePass version:  2.47 64-bit
KeePassRDP version:  1.14

Please let me know if more information is required.

**Comment by scorbin-ewi** [comment]
Upon further investigation it seems that an event is indeed generated,  I found event 5378 'The requested credentials delegation was disallowed by policy' in the windows Security log was being generated.  So apparently something in our policy is preventing this.  So this doesnt seem to be a bug in KeePassRDP but perhaps would be useful to add to the manual for future reference by others.

**Comment by iSnackyCracky** [comment]
Hi @scorbin-ewi, thanks for your report on this.

I've tried to look into this issue multiple times before (I assume this is basically the same issue as in https://serverfault.com/questions/396722/your-system-administrator-does-not-allow-the-use-of-saved-credentials-to-log-on)

Unfortunately I currently have no machine to reproduce this. I am trying to set up a lab environment to reproduce and test stuff like this though.
Could you maybe check these group-policy settings on your workstation(s):
Computer Configuration > Administrative Templates > System > Credentials Delegation > _basically any allow or deny policies_.

If I try connecting to a remote server (part of an AD domain) from my machine (not part of any AD domain, and not having defined any of these policies) saving credentials works either with or without the "_Store as Windows credentials_" checkbox.

If I enable "_Deny delegating saved credentials_" for any server (by adding `*` to the list), the connection only works with "_Store as Windows credentials_" **unchecked**. If I try turning it on instead, the connection will just ask for credentials again.

**Comment by scorbin-ewi** [comment]
Sounds very similar.  I thought for sure it would have been enabled on my machine but it actually was not configured.  It does however give the message that my system administrator does not allow the user of saved credentials.   This is from a Windows 10 machine to a Windows 2016 server, both a member of the same domain.  Some of the other servers exhibit slightly different behavior in that it simply asks for the credentials as if they were not previously provided.  In fact only 2 of my servers gave the message about not allowing stored credentials, and the rest simply asked for credentials as if they were not provided.

                I am happy to continue helping in narrowing down the issue and testing this.  If there are any other questions or ideas to try, just let me know.

Shane Corbin
Electrical Engineer/IT Administrator
Direct: (217) 893-5526
Office: (217) 892-4322

**Comment by iSnackyCracky** [comment]
> I thought for sure it would have been enabled on my machine but it actually was not configured. It does however give the message that my system administrator does not allow the user of saved credentials.

Yeah, that's the weird part. I had this happen on multiple occasions.
From a domain computer to another domain's server, from a domain computer to a server in the same domain.
Even had this happen from a non-domain computer to a domain-member server.
Happened with different versions of clients and servers too.
Never was a GPO actually configured for this.

I'll leave this issue open (obviously) and will try to gather some more information. Maybe there is another workaround than just saving credentials as "generic" type.

**Comment by NETertainer** [comment]
@scorbin-ewi Could you verify if v2.0 changes anything to that behavior?
When using the "save as windows credentials" feature, credentials are actually saved as domain credentials to the windows vault, making them a little more secure, but possibly colliding with other domain credentials.
In earlier versions additionally the credentials saved to the windows vault were not explictly marked for rdp-only usage.
Both settings might have impact on how exactly mstsc.exe tries to authenticate with a remote server, especially when it "thinks" it connects to a domain joined computer.

**Comment by scorbin-ewi** [comment]
I’ve honestly moved away from using RDP for my servers for the most part so I haven’t given it much exercise lately, but I did try to connect using the plugin and all the servers I tried seem to work just fine now.  If I remember right the problem was intermittent, so this may not be a reliable test, but so far so good.

After installation and after testing, my AV hit on KeePassRDP.unmanaged.dll.

                KeePassRDP.unmanaged.dll is malware of type Gen:Variant.Ulise.395956

It reports that it deleted the dll.  Tested after the malware report and everything still seems to work properly.  Thinking it could be a false positive, but it is still working.  Wonder if something similar was happening prior to the update as well, though it doesn’t seem to be hurting anything this time regardless of the deletion.

Shane Corbin
Electrical Engineer/IT Administrator
Direct: (217) 893-5526
Office: (217) 892-4322
Call via ***@***.***>
Chat via ***@***.***>

**Comment by NETertainer** [comment]
Thank you for trying. The unmanaged dll is a new part and not directly related to it. We could not yet determine what exactly is causing those false positives, so there are fallbacks to keep KeePassRDP working in case the dll gets removed.
Even though your results look promising there is some intransparency regarding how credentials are delegated throughout rdp sessions, so I guess we will leave the issue open for now.

**Comment by NETertainer** [comment]
Closing, as there are no similar observations made.
Feel free to reopen when necessary.
