### ISSUE TITLE
Support pre-configured .rdp files

### ISSUE THREAD

**Issue by montoner0** [iSnackyCracky/KeePassRDP#23]
**Is your feature request related to a problem? Please describe.**
A lot of options could only be configured within .rdp files, there's no command line switches for them. 

**Describe the solution you'd like**
It would be nice if this plugin could use .rdp files to run RDP sessions.

**Additional context**
This approach should considerably simplify the configuration for the plugin, since you can do all the process inside a native mstsc interface.

**Comment by iSnackyCracky** [comment]
This is an interesting idea!
I'll definitely look into this and probably somehow integrate it with the per-entry-settings (see #22).

**Comment by NETertainer** [comment]
I did some testing and stumbled upon a lot of complexity surrounding the automatic generation of rdp files.
One of the major additions would include the requirement to be able to manage certificates, as rdp files need to be signed with a trusted certificate to avoid acknowledging them on every connection attempt.
Therefore and because rdp files are generally usable already when entered as the first additional command line argument, I will close this issues as unresolvable for now.

**Comment by montoner0** [comment]
I've never seen a signed .rdp in a whole my life so this isn't an issue IMO. You could at least allow users to add their own file and use it.

**Comment by NETertainer** [comment]
@montoner0 Sorry for answering a little late. As mentioned before you can at least specify an rdp file on a per entry basis when specifiying it as the first additional mstsc parameter in the edit entry dialog.

**Comment by NETertainer** [comment]
@montoner0 Sorry for answering a little late. As mentioned before you can at least use rdp files on a per entry basis when specifying them as the first additional mstsc parameter in the edit entry dialog.

**Comment by montoner0** [comment]
This means that I need to store the files somewhere which is quite missing the whole point. If I have the file I don't need KeePass.

**Comment by NETertainer** [comment]
It is not that I would not like such functionality, it is just that I think that creating rdp files should be handled in its own plugin.
Many quetions arise when dealing with files in general. How to generate those files, where to put them for mstsc.exe to find, how to determine for how long to keep the files? Do we want to create and delete files for every connection attempt?
Apart from that, a structure would have to be implemented to transfer all those settings into something that can be saved in KeePass and back to (temporary) .rdp-files. Additionally the use of WinForms in KeePass puts some limitations on how much the gui can handle.
One other thing to keep in mind is that KeePassRDP tries to be secure. So when we implement new features we have the expectation to be doing it fully and correctly, which includes all the encryption and certificates stuff mentioned earlier, imho.

**Comment by montoner0** [comment]
My initial proposal was about to let mstsc generate the file and add it as an attachment to an entry in KeePass so you don't need to copy the already existing functionality. The plugin could tweak the files for some settings (especially those not available in the mstsc itself) but not more. 
About where to put - any suitable place, it could be %temp%, it could be some other place in a user's profile. Since the files don't usually contain any sensitive information I don't see why they should be deleted from this "cache" location, you'll need only update them in case if the file was updated in the entry.

**Comment by NETertainer** [comment]
Just to clarify. How would that be different from just putting an .rdp-file at some location and adding that as a paramter to an entry?

**Comment by montoner0** [comment]
The difference is that the files will be within the KeePass database so you can safely transfer it anywhere.

**Comment by NETertainer** [comment]
@montoner0 There is a new button in the KeePassRDP entry settings tab ![grafik](https://github.com/iSnackyCracky/KeePassRDP/assets/125803340/0d63305a-e532-47b5-ae3a-fe4e69499ecd).
It allows to configure .rdp files on a per entry basis and will be active when any of the settings differ from the defaults.
For now every entry will need its own configuration as there is no way to reference other entires yet.

**Comment by NETertainer** [comment]
@montoner0 There is a new button in the KeePassRDP entry settings tab ![grafik](https://github.com/iSnackyCracky/KeePassRDP/assets/125803340/0d63305a-e532-47b5-ae3a-fe4e69499ecd).
It allows to configure .rdp files on a per entry basis and will be active when any of the settings differ from the defaults.
For now every entry will need its own configuration as there is no way to reference other entries yet.

**Comment by montoner0** [comment]
Thanks! I'll look into this when I have an opportunity.
