### ISSUE TITLE
release 1.13 does not read correctly placeholder syntax

### ISSUE THREAD

**Issue by ilceko** [iSnackyCracky/KeePassRDP#27]
If you use {REF:...} in the password field of an entry, plugin will fail to use the credential.
This is not happening in previous release. Infact I had to revert on previous release.

Easy to reproduce:
![image](https://user-images.githubusercontent.com/74476717/175497792-df9a9732-55f4-43fd-97d4-117bfa46caf7.png)

with a setup like shown, using a master entry (I) with the correct password, the login will fail on the 1.13 release of KeePassRDP.

Sorry for my basic english. I hope this is clear, otherwise let me know how can clarify the issue.

**Comment by iSnackyCracky** [comment]
Omg.. Thank you really much for reporting this.. I have no Idea, how this happened and especially how this wasn't noticed in our daily use so far.
I already found the issue and will have a fixed version up in a few minutes probably.
