### ISSUE TITLE
Credentials not correctly filled when they are field references.

### ISSUE THREAD

**Issue by massimobalestra** [iSnackyCracky/KeePassRDP#30]
Username and password are field references of another Keepass Entry. Typically I use this field reference if I have two IPs of the same server, one main IP and one secondary IP. In the secondary entry I enter a field references to username and password of the primary one.
Opening an RDP connections the credentials are not accepted.
If I then enter the credentials in the usual Keepass way (ctrl+v) it works.
Same behaviour if "Store as windows credentials" is checked or not.
Version: 2.0.
It worked correctly in the previous version (1.13).
Thank you

**Comment by NETertainer** [comment]
I can confirm that passwords of entrys that are references are not resolved correctly while usernames are.
Sorry no one noticed beforehand, but I was already able to identify the changes necessary to make it work.
Other than that I was acutally hoping to have matched the original behavior of KeePass so I might take a look at what I have missed before releasing a fixed version.

**Comment by massimobalestra** [comment]
Thank you very much.
I really appreciate the work you are doing for this great tool.

**Comment by NETertainer** [comment]
Thank you for taking the time to report.
It must have been an oversight on my part.
Fixed with v2.0.1.

**Comment by massimobalestra** [comment]
It works great!
Thank you very much.
