### ISSUE TITLE
17 security vendors and no sandboxes flagged this file as malicious

### ISSUE THREAD

**Issue by mead3000** [iSnackyCracky/KeePassRDP#31]
v2.0.1

Malware detected in keepassrdp.unmanaged.dll

https://www.virustotal.com/gui/file/59c443a9dfb7c950876b6ab7e5a69ced7b17ab02a3cfc0354e7f83524a963ffe/detection

**Comment by NETertainer** [comment]
Fixed with v2.0.2.
https://www.virustotal.com/gui/file/843c838983bea16376cc7927385d03ecee92ccc070ff7395caff559f7fd76bad
![](https://user-images.githubusercontent.com/125803340/229285624-df1e5ab9-4bf8-4859-863b-676006580369.png)
