### ISSUE TITLE
Connect via RDS Gateway

### ISSUE THREAD

**Issue by Pyeongyang** [iSnackyCracky/KeePassRDP#32]
Hallo,

how could I connect via Windows RDS Gateway?
(the Parametersname inside an *.rdp file is _gatewayhostname:_ )

Danke im Voraus

**Comment by NETertainer** [comment]
This should be possible by adding /g <gatewayhostname> as an additional parameter in the KeePassRDP tab on the edit entry page.
![grafik](https://user-images.githubusercontent.com/125803340/234616743-a6ea5770-e4fa-4199-b82d-7718c54af96a.png)
e.g.:
![grafik](https://user-images.githubusercontent.com/125803340/234616969-04c9d845-0001-46bb-994a-41e8c0892509.png)

**Comment by NETertainer** [comment]
This should be possible by adding /g:\<gatewayhostname\> as an additional parameter in the KeePassRDP tab on the edit entry page.
![grafik](https://user-images.githubusercontent.com/125803340/234616743-a6ea5770-e4fa-4199-b82d-7718c54af96a.png)
e.g.:
![grafik](https://user-images.githubusercontent.com/125803340/234620990-777e26ee-d414-4b72-bc99-38c312c0427b.png)

**Comment by Pyeongyang** [comment]
Hi!

Thank you for the answer!
I will try to use the /g option there.

Not to create a new topic, could I ask a couple of questions right here?

Are these username (1) and password (2) used by KeePassRDP for authentification?
![rds](https://user-images.githubusercontent.com/68427606/234805230-740a17c5-67fd-4395-8bbb-fe4c311b1c8a.gif)

Could you please provide some link of how-to/set up KeePassRDP?

Thank you.

**Comment by NETertainer** [comment]
I would suggest to start with reading the information provided on the main project page: [Trigger group / folder](https://github.com/iSnackyCracky/KeePassRDP#trigger-group--folder).
Other than that most inputs and buttons are showing a general explanation when hovering, so maybe you could just try out to find what you are looking for?
