### ISSUE TITLE
Element not Found

### ISSUE THREAD

**Issue by github-tomster** [iSnackyCracky/KeePassRDP#33]
**Describe the bug**
i can only provide little infos. 🤦🏻 
it was working untill yesterday.
the keepass portable version was updated from 2.54 to 2.55.
as far as i remember rdp connections called via the icon
worked after the update 🤷🏻 

it all started at the point that i browsed through the
options of KeePassRDP. i jumped from the 'integration' register
to the 'picker' and as soom as i clicked the 'vault' register
the error [only in german available] showed up:

```
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ComponentModel.Win32Exception (0x80004005): Element nicht gefunden
   bei KeePassRDP.NativeCredentials.CredEnumerate(String filter, Credential[]& credentials)
   bei KeePassRDP.KprCredentialManager`1..ctor(IEnumerable`1 credentials, KprConfig config)
   bei KeePassRDP.KeePassRDPExt.<.ctor>b__0()
   bei System.Lazy`1.CreateValue()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Lazy`1.get_Value()
   bei KeePassRDP.KprConnectionManager.ConnectRDPtoKeePassEntry(Boolean tmpMstscUseAdmin, Boolean tmpUseCreds)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.PerformClick()
   bei KeePassRDP.KeePassRDPExt.TriggerSystem_RaisingEvent(Object sender, EcasRaisingEventArgs e)
   bei KeePass.Ecas.EcasTriggerSystem.RaiseEventObj(EcasEvent e, EcasPropertyDictionary props)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei KeePass.UI.CustomToolStripEx.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

since that point i cant start a rdp connection with credentials anymore 😿 
if i start a rdp connection without credentials it works 🙄 

OS: Win10 1809 [latest CU installed]
.NET 4.8 [latest CU installed]

restoring the KeePass backup from yesterday makes no difference 😵 
downgrade to KeePass 2.54 makes no difference 😞 
clearing .net cache did not helped 🧹 

if i downgrade to KeePassRDP 1.13.3 it works as expected 😄 
on other machines i have no issues and i was not able to reproduce the error on other machines
as the register 'vault' opens correctly on all other machines 🎲 

any hints before i `format c:\` 🤪

**Comment by github-tomster** [comment]
i found the root cause 💡 
empty the windows vault and the error shows 🙄 
so i one must not have an empty windows vault ❗

**Comment by NETertainer** [comment]
Sorry for missing your post and thank you for your findings. Will be fixed with the next version.
