### ISSUE TITLE
Keep asking for password (Gateway usage)

### ISSUE THREAD

**Issue by Metathesus** [iSnackyCracky/KeePassRDP#35]
Hi, 

1) Create an entry
2) Added Username / Password 
3) Added the adress of the target computer rdp://computer.privatedomain.local
4)  I have imported a RDP file containing the gateway adress https://subdomain.publicdomain.com:8443
5) OpenRDP Connection

It keep asking for a password. I don't know what I do wrong.

Thanks for your help!

P.S: Sorry for my english

**Comment by NETertainer** [comment]
As far as our testing went, this is supported now.
In case you are connecting to an RDS broker, the host redirected to cannot be known beforehand and no credentials can be generated this way. As a workaround take a look at #36 for automatic filling of password dialogs.

**Comment by Metathesus** [comment]
Thank you very much!
