### ISSUE TITLE
The server's authentication policy does not allow connection requests using saved credentials. Please enter new credentials.

### ISSUE THREAD

**Issue by vactirio** [iSnackyCracky/KeePassRDP#36]
Hi all,

When we try to open an RDP connection by using CTRL-M, we get the message "The server's authentication policy does not allow connection requests using saved credentials. Please enter new credentials."  which is normal because of our company policy not to store RDP passwords.

Is there anyway that keepass + KeePassRDP   bypass the restriction above and use the password stored in KeePass on those cases?

![image](https://github.com/iSnackyCracky/KeePassRDP/assets/28702022/8828e450-b875-43a4-aae9-786749fbed49)

Thank U

**Comment by NETertainer** [comment]
The next version will include an option to automatically paste credentials into the dialog.
You could also try Remote Credential Guard (https://learn.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard) using the `/remoteGuard` parameter.

**Comment by NETertainer** [comment]
You can try the new setting now:
![retry-credentials](https://github.com/iSnackyCracky/KeePassRDP/assets/125803340/0cae3fd7-3ee7-46be-ab41-6ce23ab6709a)

It will fill in and submit the password dialog once, which will also make mstsc.exe cache the credentials.

**Comment by vactirio** [comment]
This is magic!  Works perfectly!!   Thank you so much.

Andreas from Athens/Greece
