### ISSUE TITLE
Support installing from external sources

### ISSUE THREAD

**Issue by vinhins** [iSnackyCracky/KeePassRDP#40]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
Currently we download and extract to certain keepass plugin directory manually (or script), It would be nice if there is easier way to install, likely `winget install/add/upgrade keepassrdp` for example.

**Describe alternatives you've considered**
chocolaty also works

**Comment by NETertainer** [comment]
I like the idea. We will figure out if it is possible to use winget with the current exe installer.

**Comment by vinhins** [comment]
thanks!

**Comment by NETertainer** [comment]
I have made some good progress using [wixsharp](https://github.com/oleg-shilo/wixsharp), so that the next release will also be available in msi format.
As soon as we find time we will also try to publish through winget.

**Comment by NETertainer** [comment]
I have made some good progress using [wixsharp](https://github.com/oleg-shilo/wixsharp), so that the next release will be available in msi format.
As soon as we find time we try to publish through winget, too.
