### ISSUE TITLE
Quick connect button

### ISSUE THREAD

**Issue by ahoytguy** [iSnackyCracky/KeePassRDP#6]
I am looking for a way to create a button that will use KeePassRDP to open an entry quickly from the toolbar. I have attempted a custom button via a trigger, but can't figure it out. Could this be implemented via the plugin code with maybe a cool icon or something.
Totally an enhancement, but worth it if it can be done.

**Comment by iSnackyCracky** [comment]
Hi @ahoytguy,
do you mean an icon in the toolbar?
![image](https://user-images.githubusercontent.com/20481463/72284767-136eee80-3642-11ea-9d83-4e5bfe299efa.png)
I have to look into it, but I guess this should be possible somehow.
I'll let you know, if I get something useful.

**Comment by ahoytguy** [comment]
Yes, that would be great. Thank you so much.

**Comment by iSnackyCracky** [comment]
I was able to implement a button in the main toolbar, but for now it just uses the Unicode (U+1F4BB) `PERSONAL COMPUTER` character (💻), since I wasn't able to set a (custom) _icon_ yet.

You can check it out in the new [alpha release](https://github.com/iSnackyCracky/KeePassRDP/releases/tag/v1.10.0-alpha)

**Comment by ahoytguy** [comment]
From my perspective this works perfect.  I can imagine you will want to have a custom icon that represents KeePassRDP a little better, but functionally this is exactly what I was looking for.  Gota say once again, very impressed with the product and the support you provide.

**Comment by ahoytguy** [comment]
I did notice if no entry is selected the right click menu causes an exception when you go to the KeePassRDP option, also happens when using the toolbar entry, KeePassRDP.  It's a minor issue as it does not make sense to go to that menu item when you don't have an entry selected.  I thought I would report it anyway as I did see it happen.  It does allow continue so that helps.

Unhandled exception...bla, bla, bla...Object reference not set to an instance of an object.
If you need details let me know. I first notice this in the Alpha, but not sure I would ever have tried this before...as I said, who would?

**Comment by iSnackyCracky** [comment]
Oh, I see - that shouldnt happen when using the new toolbar button though (this should just show a message box saying "You have to select an entry first.")
I think I already know why this is happening (should be since the v1.9.0).
I'll probably release an updated version with a fix for this soon.

**Comment by iSnackyCracky** [comment]
Should be fixed, I'll close this for now. Maybe I'll look into the toolbar icon thing again at a later point though.
