### ISSUE TITLE
Specific characters in passwords do not work

### ISSUE THREAD

**Issue by jaspersalathe** [iSnackyCracky/KeePassRDP#8]
Hello,
some specific characters do not work in passwords. The best example is the quotation mark (character ").
I would guess, that KeePassRDP.cs:260 need proper escaping of such characters.
E.g. quotation marks at the beginning and end of the user defined strings and doubling quotation marks within the strings.
... sadly I was not able to setup the compilation environment in adequate time, so I was not able to create a patch myself.

Stuff like passwords ending with " && calc.exe" or " ; calc.exe" do not seem to have special effects besides breaking the login to remote machines.

**Comment by iSnackyCracky** [comment]
Hi @jaspersalathe,

seems reproduceable. I will definitely look into this soon.
Thank you for reporting.

**Comment by iSnackyCracky** [comment]
@jaspersalathe, you may check out the pre-release [v1.10.2-alpha](https://github.com/iSnackyCracky/KeePassRDP/releases/tag/v1.10.2-alpha). This should fix this behaviour and make the credential-saving process a bit safer overall.

**Comment by jaspersalathe** [comment]
Looks good. I was able to build it and the password ^°!"§$%&/()=?`´ßöäü+*#'|\<>²³,.-;:_{[]} works now.
Thanks a lot!
\o/

... I was having trouble while building the package, because CredentialManagement.dll is missing in the ext folder. But maybe the main reason was my lack of understanding of the build process...

**Comment by iSnackyCracky** [comment]
> ... I was having trouble while building the package, because CredentialManagement.dll is missing in the ext folder. But maybe the main reason was my lack of understanding of the build process...

Yeah, I added the CredentialManager via NuGet package first, but then I wasn't able to complete the .plgx creation, so I removed the NuGet and added the .dll manually but forgot to push this change afterwards.
I'll probably look into the whole NuGet thing in the future (because I know other Plugins are using it without issues) and generally improve the build process.
